import axios from "axios";

const BACKEND_URL = 'https://expense-d72a0-default-rtdb.firebaseio.com/';

export async function storeExpense(expenseData){
    const response = await axios.post( BACKEND_URL +'expenses.json',
        expenseData
    ); //response contains the id generated by Firebase in response.data.name;
    
    console.log(response.data);
    const id = response.data.id;
    return id;
}

export async function fetchExpenses(){
   const response = await axios.get( BACKEND_URL +'expenses.json');
   const expenses = [];

   for (const key in response.data){
        const expenseObject = {
            id: key,
            amount : response.data[key].amount,
            date:  new Date(response.data[key].date),
            name: response.data[key].name
        }
        expenses.push(expenseObject);
   }

   return expenses;
}

export function updateExpense(id, expenseData){
    return axios.put(BACKEND_URL + `expenses/${id}.json`, expenseData);
}

export function deleteExpense(id){
    return axios.delete(BACKEND_URL + `expenses/${id}.json`);
}